# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48305f02eeec94870c1f36cc9053282d55670992315e1ac2037d780ea004e2478063463de24323a7e1db0f13c4c9e88f83e6a038bd176cab150b0bf3e52d0022

test:
  secret_key_base: 4dd1ae619dd578ab0045cd5a1fa7208e10f1c425884b1ee4fce51bd403fd8e7b8be496100668da81361b73fc48a4bc2d258a5f3547425eda9c40fe5e75df2345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
